name: IPO Checker

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Black Format
        run: pipenv run black --check --diff .

      - name: Check typing
        run: pipenv run mypy ipo_checker --install-types && pipenv run mypy ipo_checker

      - name: Run tests
        run: pipenv run pytest -vvv
